# directory containing the data for each task
bench_data_root: 'eval/bench_data'

# directory where benchmark results will be dumped
results_dir: 'eval/ST_pred_results'

# directory where the vision embeddings will be dumped
embed_dataroot: 'eval/ST_data_emb'

# inference parameters
batch_size: 128
num_workers: 1

# encoders to benchmark
encoders: [
  # "resnet50",
  # "uni_v1", # you need to request the weights
  # "uni_v2", # you need to request the weights
  # "ctranspath",
  # "phikon",
  # "phikon_v2",
  # "hibou_l",
  # "kaiko-vitb8",
  # "kaiko-vitb16",
  # "kaiko-vits8",
  # "kaiko-vits16",
  # "kaiko-vitl14",
  # "lunit-vits8",
  # "conch_v1", # you need to request the weights
  # "conch_v15",
  # "gigapath", # you need to request the weights
  # "virchow", # you need to request the weights
  # "virchow2", # you need to request the weights
  # "hoptimus0", # you need to request the weights
  # "hoptimus1", # you need to request the weights
  # "musk", # you need to request the weights
  # "midnight12k",
  # "h0-mini", 
  # "openmidnight", # you need to request the weights
  # gpfm,
]

# datasets contained in `bench_data_root` to benchmark
datasets: [
  "IDC",
  # "PRAD",
  # "PAAD",
  # "SKCM",
  # "COAD",
  # "READ",
  # "CCRCC",
  # "LUNG",
  # "LYMPH_IDC",
]

dimreduce: "PCA" 