version: "2"

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
    - libvips
    - libvips-dev
    - openslide-tools

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
