# directory containing all the datasets
source_dataroot: '/mnt/ssd/paul/ST-histology-loader/bench_data'

# directory where results will be dumped
results_dir: '/mnt/sdb1/paul/ST_pred_results/'

# directory where the vision embeddings will be dumped
embed_dataroot: '/mnt/sdb1/paul/ST_data_emb'

# inference parameters
precision: 'fp32'
batch_size: 128
num_workers: 1

# encoders to benchmark
encoders: [
  "pathchatv2",
  "pathchatv2-5",
  "pathchatv3"
  #"ibot_uni",
  #"kimianet",
  #"plip",
  #"uni_v1_official",
  #"resnet50_trunc",
  #"ciga",
  #"ctranspath",
  #"phikon_official_hf",
  #"remedis",
  #"conch_v1_official",
]

# datasets contained in `source_dataroot` to benchmark
datasets: [
  "IDC",
  "PRAD",
  "PAAD",
  "SKCM",
  "COAD",
  "READ",
  "CCRCC",
  "HCC",
  "LUNG",
  "LYMPH_IDC",
]