# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Hest tests

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Download test assets
      run: |
        wget -O assets.zip "https://www.dropbox.com/scl/fi/55xel2c2mitlvce0msukr/assets.zip?rlkey=dfskodyyqc99cikzzboqlfx4p&dl=1"
    
    - name: Download model
      run: |
        wget -O deeplabv3_seg_v3.ckpt "https://huggingface.co/pauldoucet/tissue-detector/resolve/main/deeplabv3_seg_v3.ckpt?download=true" && mv deeplabv3_seg_v3.ckpt models/

    - name: Unzip test assets
      run: |
        unzip assets.zip && mv assets tests/
     
    - name: Install python dependencies
      run: |
        python -m pip install -e .
    - name: Install apt dependencies
      run: |
        sudo apt install libvips libvips-dev openslide-tools

    - name: Run reader tests
      run: |
        python tests/reader_tests.py
      continue-on-error: true

    - name: Run hestdata tests
      run: |
        python tests/hestdata_tests.py
