# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Hest tests

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install python dependencies
      run: |
        python -m pip install -e .
    - name: Install apt dependencies
      run: |
        apt install libvips libvips-dev openslide-tools
    - name: Run reader tests
      run: |
        python reader_tests.py
    - name: Run hestdata tests
      run: |
        python hestdata_tests.py
